language: java
jdk: openjdk14
branches:
  only:
  - master
script: mvn clean install
after_success:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://idrinth.de/codacy-coverage-reporter-assembly-latest.jar
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml
after_failure:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://idrinth.de/codacy-coverage-reporter-assembly-latest.jar
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml
