language: java
jdk: openjdk14
branches:
  only:
  - master
script: mvn clean install
after_success: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r ./target/jacoco/jacoco.xml
after_failure: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r ./target/jacoco/jacoco.xml
